// %% license-end-token %%

//
// This file was generated by Coral RPC.
//
// WARNING: Auto-generated code. Do not modify.
//

#ifndef SEARCHSERVICE_CLIENT_STUB_H
#define SEARCHSERVICE_CLIENT_STUB_H

#include "RpcClientResource.h"
#include "tutorial.pb.h"

namespace tutorial {

class  SearchServiceClientStub :
public coral::rpc::RpcClientResource {
public:

   explicit SearchServiceClientStub( coral::rpc::RpcClient &client );
   ~SearchServiceClientStub();

   void Search(
      const Person& request,
      Person_PhoneNumber& response,
      coral::rpc::AsyncRpcSupervisor* supervisor = NULL ) throw (coral::rpc::RpcException);

}; // End SearchServiceClientStub

}  // End namespace tutorial

#endif // SEARCHSERVICE_CLIENT_STUB_H
