# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='rpctest',
  serialized_pb='\n\x10\x63\x61lculator.proto\x12\x07rpctest\"0\n\x0f\x43\x61lculatorAddIn\x12\r\n\x05\x66irst\x18\x01 \x02(\x05\x12\x0e\n\x06second\x18\x02 \x02(\x05\"\"\n\x10\x43\x61lculatorAddOut\x12\x0e\n\x06result\x18\x01 \x02(\x05\"0\n\x0f\x43\x61lculatorSubIn\x12\r\n\x05\x66irst\x18\x01 \x02(\x05\x12\x0e\n\x06second\x18\x02 \x02(\x05\"\"\n\x10\x43\x61lculatorSubOut\x12\x0e\n\x06result\x18\x01 \x02(\x05\"0\n\x0f\x43\x61lculatorMulIn\x12\r\n\x05\x66irst\x18\x01 \x02(\x05\x12\x0e\n\x06second\x18\x02 \x02(\x05\"\"\n\x10\x43\x61lculatorMulOut\x12\x0e\n\x06result\x18\x01 \x02(\x05\"0\n\x0f\x43\x61lculatorDivIn\x12\r\n\x05\x66irst\x18\x01 \x02(\x05\x12\x0e\n\x06second\x18\x02 \x02(\x05\"\"\n\x10\x43\x61lculatorDivOut\x12\x0e\n\x06result\x18\x01 \x02(\x05\"\x17\n\x15\x43\x61lculatorGetNumOpsIn\"(\n\x16\x43\x61lculatorGetNumOpsOut\x12\x0e\n\x06result\x18\x01 \x02(\x05\x42\'\n\x13\x63om.example.rpctestB\x10\x43\x61lculatorProtos')




_CALCULATORADDIN = _descriptor.Descriptor(
  name='CalculatorAddIn',
  full_name='rpctest.CalculatorAddIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='rpctest.CalculatorAddIn.first', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second', full_name='rpctest.CalculatorAddIn.second', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=77,
)


_CALCULATORADDOUT = _descriptor.Descriptor(
  name='CalculatorAddOut',
  full_name='rpctest.CalculatorAddOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='rpctest.CalculatorAddOut.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=79,
  serialized_end=113,
)


_CALCULATORSUBIN = _descriptor.Descriptor(
  name='CalculatorSubIn',
  full_name='rpctest.CalculatorSubIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='rpctest.CalculatorSubIn.first', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second', full_name='rpctest.CalculatorSubIn.second', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=115,
  serialized_end=163,
)


_CALCULATORSUBOUT = _descriptor.Descriptor(
  name='CalculatorSubOut',
  full_name='rpctest.CalculatorSubOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='rpctest.CalculatorSubOut.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=165,
  serialized_end=199,
)


_CALCULATORMULIN = _descriptor.Descriptor(
  name='CalculatorMulIn',
  full_name='rpctest.CalculatorMulIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='rpctest.CalculatorMulIn.first', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second', full_name='rpctest.CalculatorMulIn.second', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=201,
  serialized_end=249,
)


_CALCULATORMULOUT = _descriptor.Descriptor(
  name='CalculatorMulOut',
  full_name='rpctest.CalculatorMulOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='rpctest.CalculatorMulOut.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=251,
  serialized_end=285,
)


_CALCULATORDIVIN = _descriptor.Descriptor(
  name='CalculatorDivIn',
  full_name='rpctest.CalculatorDivIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='rpctest.CalculatorDivIn.first', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second', full_name='rpctest.CalculatorDivIn.second', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=287,
  serialized_end=335,
)


_CALCULATORDIVOUT = _descriptor.Descriptor(
  name='CalculatorDivOut',
  full_name='rpctest.CalculatorDivOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='rpctest.CalculatorDivOut.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=337,
  serialized_end=371,
)


_CALCULATORGETNUMOPSIN = _descriptor.Descriptor(
  name='CalculatorGetNumOpsIn',
  full_name='rpctest.CalculatorGetNumOpsIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=373,
  serialized_end=396,
)


_CALCULATORGETNUMOPSOUT = _descriptor.Descriptor(
  name='CalculatorGetNumOpsOut',
  full_name='rpctest.CalculatorGetNumOpsOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='rpctest.CalculatorGetNumOpsOut.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=398,
  serialized_end=438,
)

DESCRIPTOR.message_types_by_name['CalculatorAddIn'] = _CALCULATORADDIN
DESCRIPTOR.message_types_by_name['CalculatorAddOut'] = _CALCULATORADDOUT
DESCRIPTOR.message_types_by_name['CalculatorSubIn'] = _CALCULATORSUBIN
DESCRIPTOR.message_types_by_name['CalculatorSubOut'] = _CALCULATORSUBOUT
DESCRIPTOR.message_types_by_name['CalculatorMulIn'] = _CALCULATORMULIN
DESCRIPTOR.message_types_by_name['CalculatorMulOut'] = _CALCULATORMULOUT
DESCRIPTOR.message_types_by_name['CalculatorDivIn'] = _CALCULATORDIVIN
DESCRIPTOR.message_types_by_name['CalculatorDivOut'] = _CALCULATORDIVOUT
DESCRIPTOR.message_types_by_name['CalculatorGetNumOpsIn'] = _CALCULATORGETNUMOPSIN
DESCRIPTOR.message_types_by_name['CalculatorGetNumOpsOut'] = _CALCULATORGETNUMOPSOUT

class CalculatorAddIn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORADDIN

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorAddIn)

class CalculatorAddOut(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORADDOUT

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorAddOut)

class CalculatorSubIn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORSUBIN

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorSubIn)

class CalculatorSubOut(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORSUBOUT

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorSubOut)

class CalculatorMulIn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORMULIN

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorMulIn)

class CalculatorMulOut(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORMULOUT

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorMulOut)

class CalculatorDivIn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORDIVIN

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorDivIn)

class CalculatorDivOut(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORDIVOUT

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorDivOut)

class CalculatorGetNumOpsIn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORGETNUMOPSIN

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorGetNumOpsIn)

class CalculatorGetNumOpsOut(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CALCULATORGETNUMOPSOUT

  # @@protoc_insertion_point(class_scope:rpctest.CalculatorGetNumOpsOut)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023com.example.rpctestB\020CalculatorProtos')
# @@protoc_insertion_point(module_scope)
