// %% license-end-token %%

//
// This file was generated by Coral RPC.
//
// WARNING: Auto-generated code. Do not modify.
//

#include "SearchServiceClientStub.h"

using namespace coral::rpc;
using namespace tutorial;

//-----------------------------------------------------------------------------
SearchServiceClientStub::SearchServiceClientStub( RpcClient &client )
   : RpcClientResource( client, "SearchService" )
{
}

//-----------------------------------------------------------------------------
SearchServiceClientStub::~SearchServiceClientStub()
{
}

//-----------------------------------------------------------------------------
void SearchServiceClientStub::Search(
   const Person&    request,
   Person_PhoneNumber&         response,
   AsyncRpcSupervisor* supervisor ) throw(coral::rpc::RpcException)
{
   if ( call( "Search", request, response, supervisor ) == false )
   {
      throw getLastError();
   }
}


